Feat/vault logic
QuinoaDao/protocol-v1 pull request #12
Opened 2023-01-25 09:57 UTC by Seomingyun

## Summary

23일 데일리 미팅 진행 후 withdraw/deposit 관련 함수 제외하고 진행
* state variables 세팅
* constructor 세팅
* get/set/update 함수 등 작성

관련 회의록 :  https://www.notion.so/quinoaprotocol/Daily-eea1084cca7940f2af27adc2d7773c0b

**Issue Number**
#11 
#3 

**PR Type**

- [ ] Bugfix
- [x] Feature
- [ ] Design
- [ ] Test code
- [ ] Other... Please describe:

## Description 

1. function 이름 변경
    dollar기준: value
    amount기준: balance
2. function 로직 작성
    interface 기준;
    * addAsset
    * updateWeight
    * updateOracleAddress
    * currentAssets
    * checkAsset
    * assetBalance
    * assetFloatBalance
    * portfolioValue
    * assetValue
    * totalFloatValue
3. 주석 작성

## Code Review Checklist

- [ ] 주석 확인(영어가 미숙하네요)
- [ ] constructor에서 parameter로 assetAddresses_, oracleAddresses_ 설정
- [ ] 기존에 회의했던 value/balance 관련 function 5개(assetBalance, assetFloatBalance, portfolioValue, assetValue, totalFloatValue) 로직이 제대로 구현되어 있는지
- [ ] assetFloatValue 함수 추가한 것 확인 부탁

## Other information
노션에 관련 내용 옮겨 놓음
https://www.notion.so/quinoaprotocol/MVP-1-Smart-contract-A-3b28624b5e27433ab08796a1d473d658

Contract 개발 사항 정리 > Product func 확인

2023-01-25 10:01 UTC, Seomingyun commented
논의사항 1 : chainlink oracle 관련

예전에 chainlink oracle address를 관리하는 방법으로 2가지를 제안했었음.
1. product contract 상에서 asset params로 관리
2. chainlink gateway에서 asset address와 oracle address를 mapping시켜주는 contract를 생성

그때, 2번 방법은 <해당 방법은 library로 구현 불가능 -> token이 추가되면 그 list를 update해줘야 함 -> 불필요한 가스비 낭비아닐까?> 하는 생각에 반려했었는데, 
코드를 구현하다 보니 oracle address의 유효성을 검증할 방법이 없다는 것을 깨달았음 ㅜ.ㅜ
(물론 이건 asset address로 마찬가지이긴 하지만, 그래도...)

그래서 관련해서 논의가 필요할 듯 함
1. 지금 이대로 간다
2. 지금 당장 2로 바꾼다
3. 시간이 남으면 2로 바꾼다 (이때 assets[]와 strategies[]도 같이 수정)

2023-01-25 10:37 UTC, wakii commented on contracts/Product.sol
> +    using Math for uint256;
8.10^에서도 Math 필요한가요?

2023-01-25 10:39 UTC, wakii commented on contracts/Product.sol
> +    uint256 private _sinceDate;
private으로 하는 이유가 있나요??

2023-01-25 10:42 UTC, wakii commented on contracts/Product.sol
> +        require((floatRatio_ < 0) || (floatRatio_ > 100000), "Invalid float ratio");
이거 ! 붙여야 함

2023-01-25 10:43 UTC, wakii commented on contracts/Product.sol
> +    function currentAssets() external view override returns(AssetParams[] memory) {
생각해보니 이거 있어서,
AssetParmams 얘네 private으로 해도 될 것 같은데, 맞나요? 
둘중에 뭐가 낫나요?

2023-01-25 10:46 UTC, wakii commented on contracts/Product.sol
> +                    assets[j].oracleAddress = assetOracles[i];
얘도 0x00 아닌거 require 넣는게 낫겠지?

2023-01-25 10:47 UTC, wakii commented on contracts/Product.sol
>      uint256 floatRatio;
얘도 visibility 설정하는게 어떨까요?

2023-01-25 10:48 UTC, wakii commented on contracts/Product.sol
> +    function currentFloatRatio() public view returns(uint256) {
floatRatio public일 경우, currentFloatRatio 는 필요 없을듯.
private + get함수 OR public선택 필요할둣

2023-01-25 10:50 UTC, wakii commented on contracts/Product.sol
> +    ///It is recommended to call updateWeight method after calling this method.
///@dev

2023-01-25 10:58 UTC, wakii requested changes

2023-01-25 10:58 UTC, wakii commented on contracts/Product.sol
>      function deposit(address assetAddress, uint256 assetAmount, address receiver) external returns (uint256 shares) {
이름 바뀐 것 같은데?

2023-01-25 10:58 UTC, wakii commented on contracts/Product.sol
이거 ! 붙여야 함

2023-01-25 10:58 UTC, wakii commented on contracts/Product.sol
> +            uint256 currentBalance = assetFloatBalance(assets[i].assetAddress); // float balance
이거 assetFloatBalance 말고 assetBalance(assets[i].assetAddress)가 맞긴 한데,

float 충분 한 경우랑, 부족한경우에 따라 strategy에서 가져오는거 필요헤서, 다른변수로 assetFloatBalance 가져오긴 해야 함

2023-01-26 02:42 UTC, Seomingyun commented on contracts/Product.sol
> +    using Math for uint256;
ㅇㅅㅇ ? 뭔가 다른가여 8.10^ 부터는 ?.?

2023-01-26 02:44 UTC, Seomingyun commented on contracts/Product.sol
> +    uint256 private _sinceDate;
erc20에서 name, symbol이 private이길래 통일시키고 싶어서 private으로 썻어요 큰 의미는 X

2023-01-26 02:45 UTC, Seomingyun commented on contracts/Product.sol
> +    function currentAssets() external view override returns(AssetParams[] memory) {
struct ㅈㅏ체를 private으로 하는거 말하는건가여 ?

2023-01-26 03:11 UTC, wakii commented on contracts/Product.sol
> +    using Math for uint256;
safeMath는 안써도 되는데, Math는 잘 모르겠네요.

2023-01-26 03:11 UTC, wakii commented on contracts/Product.sol
> +    uint256 private _sinceDate;
다른 함수들이랑 변수들도 그렇고, visibility best practice를 알아봐야 할 듯 합니다.

2023-01-26 03:12 UTC, wakii commented on contracts/Product.sol
> +    function currentAssets() external view override returns(AssetParams[] memory) {
이것도 visibility best practice랑 같은 논의

2023-01-26 03:42 UTC, wakii commented
> 논의사항 : chainlink oracle 관련
> 
> 예전에 chainlink oracle address를 관리하는 방법으로 2가지를 제안했었음.
> 
> 1. product contract 상에서 asset params로 관리
> 2. chainlink gateway에서 asset address와 oracle address를 mapping시켜주는 contract를 생성
> 
> 그때, 2번 방법은 <해당 방법은 library로 구현 불가능 -> token이 추가되면 그 list를 update해줘야 함 -> 불필요한 가스비 낭비아닐까?> 하는 생각에 반려했었는데, 코드를 구현하다 보니 oracle address의 유효성을 검증할 방법이 없다는 것을 깨달았음 ㅜ.ㅜ (물론 이건 asset address로 마찬가지이긴 하지만, 그래도...)
> 
> 그래서 관련해서 논의가 필요할 듯 함
> 
> 1. 지금 이대로 간다
> 2. 지금 당장 2로 바꾼다(수정 후 pr merge)
> 3. 시간이 남으면 2로 바꾼다 (이때 assets[]와 strategies[]도 같이 수정)

2023-01-26 03:47 UTC, Seomingyun commented
> > 논의사항 : chainlink oracle 관련
> > 예전에 chainlink oracle address를 관리하는 방법으로 2가지를 제안했었음.
> > 
> > 1. product contract 상에서 asset params로 관리
> > 2. chainlink gateway에서 asset address와 oracle address를 mapping시켜주는 contract를 생성
> > 
> > 그때, 2번 방법은 <해당 방법은 library로 구현 불가능 -> token이 추가되면 그 list를 update해줘야 함 -> 불필요한 가스비 낭비아닐까?> 하는 생각에 반려했었는데, 코드를 구현하다 보니 oracle address의 유효성을 검증할 방법이 없다는 것을 깨달았음 ㅜ.ㅜ (물론 이건 asset address로 마찬가지이긴 하지만, 그래도...)
> > 그래서 관련해서 논의가 필요할 듯 함
> > 
> > 1. 지금 이대로 간다
> > 2. 지금 당장 2로 바꾼다(수정 후 pr merge)
> > 3. 시간이 남으면 2로 바꾼다 (이때 assets[]와 strategies[]도 같이 수정)
> 
> 이거 2번으로 해도, oracle address 유효성 검증에 대한 문제 남는거 아닌가요??

> gateway는 우리가 관리하는거니 유효성 검증이 크게 필요하지는 않져
위에서 유효성 검증을 못한다는 의미는 진짜 쌩 모르는 검증되지 못한 사람이 DAC이 되어서 악의적으로 올리는 경우를 생각하고 한 말이었삼

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
> +    uint256 private _sinceDate;
흠.. Product를 상속해서 다른 contract를 쓸 일이 없으니 vault 자체의 속성?을 나타내는 값들은 private으로 통일하는게 나을듯요 
assets[]랑 strategies[]는 그냥 public으로 냅두고요

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
>      uint256 floatRatio;
private으로 설정하겠음

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
require((floatRatio_ < 0) || (floatRatio_ > 100000), "Invalid float ratio");
여기 맞죠 ? 부등호는 맨날 헷갈리는

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
> +                    assets[j].oracleAddress = assetOracles[i];
넹

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
> +    function currentFloatRatio() public view returns(uint256) {
private 설정하겠음(위에 참고)

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
> +    ///It is recommended to call updateWeight method after calling this method.
왜 dev로 쓰는게 나아 ? 그냥 사람들도 호출할 수 있는 함수잖어
글고 추천 한다는 주석은 addAsset 주석인데 왜 저깃는지 모르겟넹 ㅇㅂㅇ

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
> +            uint256 currentBalance = assetFloatBalance(assets[i].assetAddress); // float balance
옛날 버전이랑 비교하는게 넘 헷갈리기도 하고 ㅇㅂㅇ .. 
rebalancing은 내가 잘 모르니까 오빠가 그냥 수정해서 써쥬ㅓ

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
>      function deposit(address assetAddress, uint256 assetAmount, address receiver) external returns (uint256 shares) {
정확히 어디 ?.? 좀 포괄적으로 나와서 어디인지 모르것넹
<img width="902" alt="image" src="https://user-images.githubusercontent.com/80940909/214749311-b75bd9e9-b800-4db8-8dda-57f5baddea9f.png">

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
> +    using Math for uint256;
음 Math는 Math.Rounding 때문에 넣어놓은거라 일단 넣어놓을게요 더 리서치가 필요한듯

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
> +    uint256 private _sinceDate;
내가 위에서 private으로 통일하자고 한 이유는 getterr가 있는 이상 private이랑 public 차이는 직접 접근이 가능하냐, 아니냐인것 같은데 
1. 딱히 Product를 상속하거나, 아니면 다른 interface로 갖고 왔을 때 굳이 직접 접근을 할 일이 없어보임
2. openzeppelin에서 erc20에서 name과 symbol이 private이니까(물론 다른 상태 변수들도 다 private이긴 함) 통일성을 주자
라는 의도였당 ㅇㅂㅇ 
best practice는 잘 모르겠고 여러 예시 봤을 때 그냥 작성자가 자기 의도대로 정하는거 같긴 혀

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
>      function deposit(address assetAddress, uint256 assetAmount, address receiver) external returns (uint256 shares) {
자세히 설명해줬으면 좋겟당 난 맨날 보던 코드라 어디가 바뀐건지 헷갈리는 군 ...

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
>      function deposit(address assetAddress, uint256 assetAmount, address receiver) external returns (uint256 shares) {
바뀐게 아니라 잘못 썻단 뜻인가 ?! <assets[i].oracleAddress> 이거때문에 수정할거긴한디 이름 바뀐것도 알려쥬 ~, ~

2023-01-26 03:50 UTC, Seomingyun commented on contracts/Product.sol
> +    function currentAssets() external view override returns(AssetParams[] memory) {
근데 struct는 visibility 설정 못하지 않나여 ?/?

2023-01-26 03:51 UTC, wakii commented on contracts/Product.sol
> +    uint256 private _sinceDate;
그럼 밍 의도대로 고고고

2023-01-26 03:56 UTC, wakii requested changes

2023-01-26 03:56 UTC, wakii commented on contracts/Product.sol
네 
require(!(floatRatio < 0 || (floatRatio_ > 100000))), "Invalid float ratio");
aka
require((floatRatio > 0 && floatRatio_ < 100000, "invalid");

2023-01-26 03:56 UTC, wakii commented on contracts/Product.sol
> +    function currentAssets() external view override returns(AssetParams[] memory) {
아 그런가요?? 무조건 public?

2023-01-26 03:56 UTC, wakii commented on contracts/Product.sol
> +    ///It is recommended to call updateWeight method after calling this method.
///@dev가 dev들이 쓰는 함수라는 건가?? dev들이 참고할만한 내용인줄 알았는뎅 ㅋㅋㅋㅋ

2023-01-26 04:00 UTC, Seomingyun commented on contracts/Product.sol
> +    ///It is recommended to call updateWeight method after calling this method.
마자 ! 근데 저건 dev들만 참고할만한 내용뿐만 아니라 그냥 유저들도 쓸 수 있는 함수니까 유저들한테도 필요한 설명 아닌가 싶어서 그렇게 말한거였우

2023-01-26 04:02 UTC, Seomingyun commented on contracts/Product.sol
> +    ///It is recommended to call updateWeight method after calling this method.
그럼 관련 함수들 다 dev로 바꿀게여~,~

2023-01-26 04:02 UTC, wakii commented on contracts/Product.sol
> +    ///It is recommended to call updateWeight method after calling this method.
아 저거 recommend 말한 거였어!

2023-01-26 04:03 UTC, wakii commented
> 

굿! 그럼 2번으로 하시죠!

2023-01-26 04:03 UTC, Seomingyun commented on contracts/Product.sol
> +    ///It is recommended to call updateWeight method after calling this method.
엑 다시 수정하겟다 ..

2023-01-26 04:04 UTC, wakii commented
> > > 논의사항 : chainlink oracle 관련
> > > 예전에 chainlink oracle address를 관리하는 방법으로 2가지를 제안했었음.
> > > 
> > > 1. product contract 상에서 asset params로 관리
> > > 2. chainlink gateway에서 asset address와 oracle address를 mapping시켜주는 contract를 생성
> > > 
> > > 그때, 2번 방법은 <해당 방법은 library로 구현 불가능 -> token이 추가되면 그 list를 update해줘야 함 -> 불필요한 가스비 낭비아닐까?> 하는 생각에 반려했었는데, 코드를 구현하다 보니 oracle address의 유효성을 검증할 방법이 없다는 것을 깨달았음 ㅜ.ㅜ (물론 이건 asset address로 마찬가지이긴 하지만, 그래도...)
> > > 그래서 관련해서 논의가 필요할 듯 함
> > > 
> > > 1. 지금 이대로 간다
> > > 2. 지금 당장 2로 바꾼다(수정 후 pr merge)
> > > 3. 시간이 남으면 2로 바꾼다 (이때 assets[]와 strategies[]도 같이 수정)
> > 
> > 
> > 이거 2번으로 해도, oracle address 유효성 검증에 대한 문제 남는거 아닌가요??
> 
> gateway는 우리가 관리하는거니 유효성 검증이 크게 필요하지는 않져 위에서 유효성 검증을 못한다는 의미는 진짜 쌩 모르는 검증되지 못한 사람이 DAC이 되어서 악의적으로 올리는 경우를 생각하고 한 말이었삼

굿 그럼 2번으로 하시죠!

2023-01-26 04:11 UTC, Seomingyun commented on contracts/Product.sol
> +    function currentAssets() external view override returns(AssetParams[] memory) {
움 .. 그렇다기 보다는 struct는 일종의 type을 만드는거 같은 느낌이라서 visibility라는 개념 자체가 없는듯 ?.?

2023-01-26 04:15 UTC, Seomingyun commented on contracts/Product.sol
> +    function currentAssets() external view override returns(AssetParams[] memory) {
1. struct는 custom type을 정의하는 느낌이잖여 ?? 그래서 내 생각엔 visibility라는 개념이 적용 안될 거 같어
2. 그냥 코드 상에서 visibility 설정해주면 오류가 난당
3. 근데 interface나 contract 상에서 정의한 struct를 끌고 와서 사용할 수 있거든?? 이렇게 치면 public에 가까운 듯 하당

2023-01-26 04:16 UTC, wakii commented on contracts/Product.sol
> +    function currentAssets() external view override returns(AssetParams[] memory) {
아 그렇구만.굿굿

2023-01-26 04:19 UTC, Seomingyun commented on contracts/Product.sol
후자 ~,~에 >= <= 로 넣어서 변경했당

2023-01-26 04:20 UTC, wakii approved these changes

2023-01-26 04:20 UTC, merged